jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: latest

      - name: Run Deno Build Tasks
        run: |
          deno task build:linux
          deno task build:linuxarm
          deno task build:mac
          deno task build:macarm
          deno task build:windows

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dinosonic-binaries
          path: |
            dist/dinosonic-linux-x86
            dist/dinosonic-linux-aarch64
            dist/dinosonic-mac-x86
            dist/dinosonic-mac-aarch64
            dist/dinosonic-win-x86.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dinosonic-binaries
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/dinosonic-linux-x86
            dist/dinosonic-linux-aarch64
            dist/dinosonic-mac-x86
            dist/dinosonic-mac-aarch64
            dist/dinosonic-win-x86.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
